version: 2
jobs:
  build:
    working_directory: ~/rytr_test
    docker:
      - image: circleci/buildpack-deps
    steps:
      - checkout:
      - run:
          environment:
            TZ: Asia/Tokyo
          command: |
            sudo apt install ocaml
            bash setup.sh
      - run:
          name: base.sld のテスト
          command: |
            bash base_test.sh
      - run:
          name: contest.sld のテスト
          command: |
            bash contest_test.sh
      - store_artifacts:
          path: ~/rytr_test/simulator/base.ppm
      - store_artifacts:
          path: ~/rytr_test/simulator/contest.ppm
workflows:
  version: 2
  normal_workflow:
    jobs:
      - build
  schedule_workflow:
    triggers:
      - schedule:
          cron: "0,30 * * * *" # 30分に1回
          filters:
            branches:
              only:
                - master
    jobs:
      - build