version: 2
jobs:
  build:
    working_directory: ~/rytr_test
    docker:
      - image: circleci/buildpack-deps
    steps:
      - checkout:
      - run:
          environment:
            TZ: Asia/Tokyo
          command: |
            sudo apt install ocaml
            bash install.sh
      - run:
          name: contest.sld (128*128) のテスト
          command: |
            cd simulator
            ./sim -t rytl128.bin -dt sld/contest.sld -ob contest128.ppm -st setup
          no_output_timeout: 2h
      - run:
          name: contest.sld のテスト
          command: |
            cd simulator
            ./sim -t rytl.bin -dt sld/contest.sld -ob contest.ppm -st setup
          no_output_timeout: 2h
      - store_artifacts:
          path: ~/rytr_test/simulator/contest.ppm
      - store_artifacts:
          path: ~/rytr_test/Compiler/raytrace.s
      - store_artifacts:
          path: ~/rytr_test/assembler/rytl.bin
workflows:
  version: 2
  normal_workflow:
    jobs:
      - build
  schedule_workflow:
    triggers:
      - schedule:
          cron: "0 * * * *" # 1時間に1回
          filters:
            branches:
              only:
                - master
    jobs:
      - build